[agent]
  interval = "10s"

[[inputs.mqtt_consumer]]
  servers = ["tcp://192.168.137.1:1883"]
  topics = [
    "sites/#"
  ]
  
  ## QoS
  qos = 0
  
  ## Connection timeout
  connection_timeout = "30s"
  
  ## Client ID
  client_id = "telegraf"
  
  ## Data format
  data_format = "json"

  ## TLS Configuration
  tls_ca = "/etc/telegraf/certs/ca.crt"
  # tls_cert = "/etc/telegraf/certs/client.crt"  # Only if using client certificates
  # tls_key = "/etc/telegraf/certs/client.key"   # Only if using client certificates
  insecure_skip_verify = false  # Set to true only for testing
  

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8181"]
  token = "apiv3_2AXnjp9Q8557cGsII_ar8e82PDACpNMg9QDwzKYWLmpDUkB6UaK-iyzXwyKIYD5VAeshVNxsP2Q7w_Urq6v8fw"
  organization = ""
  bucket = "main"
