[agent]
  interval = "10s"
  flush_interval = "10s"
  hostname = "telegraf"


# ============================================
# QoS 0 — température, humidité, pression
# ============================================
[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = [  
    "cesi-strasbourg/+/+/temperature",
    "cesi-strasbourg/+/+/humidity",
    "cesi-strasbourg/+/+/pressure",
  ]
  qos = 0
  client_id = "telegraf-qos0"
  connection_timeout = "30s"
  data_format = "json"

  tag_keys = ["sensor-id"]

  [[inputs.mqtt_consumer.topic_parsing]]
    topic       = "+/+/+/+"
    measurement = "_/_/_/measurement"
    tags        = "site/building/room/_"


# ============================================
# QoS 1 — qualité de l'air (at-least-once)
# ============================================

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = [
    "cesi-strasbourg/+/+/airquality",
  ]
  qos = 1
  client_id = "telegraf-qos1"   # ⚠️ client_id différent obligatoire
  connection_timeout = "30s"
  data_format = "json"
  
  tag_keys = ["sensor-id"]


  [[inputs.mqtt_consumer.topic_parsing]]
    topic       = "+/+/+/+"
    measurement = "_/_/_/measurement"
    tags        = "site/building/room/_"


# ============================================
# OUTPUT
# ============================================

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8181"]
  token = "apiv3_2AXnjp9Q8557cGsII_ar8e82PDACpNMg9QDwzKYWLmpDUkB6UaK-iyzXwyKIYD5VAeshVNxsP2Q7w_Urq6v8fw"
  organization = ""
  bucket = "main"
